"""AI insights: analyses, crop vision, model cards (FR-A5, precision agriculture)."""
from __future__ import annotations

from typing import Annotated

import numpy as np
from fastapi import APIRouter, Depends, Query

from ..core.config import get_settings
from ..core.deps import DbSession, PagingDep, rate_limit, require_permission
from ..core.errors import ValidationFailed
from ..core.permissions import P
from ..models import AIAnalysis
from ..repositories import paginate, visible
from ..schemas import AIAnalysisOut, CropImageRequest, Page

router = APIRouter(prefix="/ai", tags=["AI"], dependencies=[Depends(rate_limit)])


@router.get("/analyses", response_model=Page[AIAnalysisOut], summary="List AI analyses")
def list_analyses(db: DbSession, paging: PagingDep,
                  principal: Annotated[object, Depends(require_permission(P.AI_READ))],
                  analysis_type: str | None = Query(default=None),
                  level: str | None = Query(default=None)) -> Page[AIAnalysisOut]:
    query = visible(AIAnalysis, principal.role, principal.org_id).order_by(
        AIAnalysis.created_at.desc())
    if analysis_type:
        query = query.where(AIAnalysis.analysis_type == analysis_type.upper())
    if level:
        query = query.where(AIAnalysis.level == level.upper())
    rows, total = paginate(db, query, paging.page, paging.page_size)
    return Page[AIAnalysisOut](items=[AIAnalysisOut.model_validate(r) for r in rows], total=total,
                               page=paging.page, page_size=paging.page_size)


@router.post("/crop-vision", summary="Classify crop leaf condition from an image")
def crop_vision(payload: CropImageRequest, db: DbSession,
                principal: Annotated[object, Depends(require_permission(P.AI_RUN))]) -> dict:
    """Accepts a flat pixel array, or a `simulate_label` to generate a synthetic patch
    (clearly marked DEMO/SIMULATION)."""
    from ai.data.generate import CROP_CLASSES, leaf_patch
    from ai.vision import IMAGE_SIZE, classify

    settings = get_settings()
    simulated = False
    if payload.pixels:
        expected = payload.size * payload.size * 3
        if len(payload.pixels) != expected:
            raise ValidationFailed(
                f"pixels must contain exactly {expected} values for size {payload.size}")
        image = np.array(payload.pixels, dtype=np.float32).reshape(
            payload.size, payload.size, 3).clip(0.0, 1.0)
    elif payload.simulate_label:
        label = payload.simulate_label.upper()
        if label not in CROP_CLASSES:
            raise ValidationFailed(f"simulate_label must be one of {CROP_CLASSES}")
        image = leaf_patch(label, IMAGE_SIZE, np.random.default_rng())
        simulated = True
    else:
        raise ValidationFailed("Provide either 'pixels' or 'simulate_label'")

    result = classify(image, model_dir=str(settings.repo_root / "ai" / "models"))
    analysis = AIAnalysis(
        org_id=principal.org_id, analysis_type="CROP_VISION", subject_type="Field",
        subject_id=payload.field_id or "unassigned", score=result["confidence"],
        level=result["label"], reasons=[result["advice"]],
        evidence={"probabilities": result["probabilities"], "simulated_input": simulated},
        model_version=result["model_version"], degraded=result["degraded"])
    db.add(analysis)
    db.commit()
    return {**result, "analysis_id": analysis.id,
            "input_marking": "DEMO/SIMULATION" if simulated else "CALLER_SUPPLIED"}


@router.get("/model-cards", summary="Model cards for every deployed model")
def model_cards(principal: Annotated[object, Depends(require_permission(P.AI_READ))]) -> dict:
    from ai.anomaly import model_card as anomaly_card
    from ai.vision import model_card as vision_card

    settings = get_settings()
    model_dir = str(settings.repo_root / "ai" / "models")
    import json
    from pathlib import Path

    fraud_path = Path(model_dir) / "fraud_model_card.json"
    fraud_card = json.loads(fraud_path.read_text()) if fraud_path.is_file() else {
        "status": "not_trained"}
    return {"anomaly": anomaly_card(model_dir), "crop_vision": vision_card(model_dir),
            "fraud": fraud_card,
            "marking": "All models are trained on synthetic data generated by this repository."}


@router.get("/summary", summary="AI activity summary")
def summary(db: DbSession,
            principal: Annotated[object, Depends(require_permission(P.AI_READ))]) -> dict:
    from sqlalchemy import func, select

    query = select(AIAnalysis.analysis_type, AIAnalysis.level, func.count()).group_by(
        AIAnalysis.analysis_type, AIAnalysis.level)
    if not principal.is_cross_tenant:
        query = query.where(AIAnalysis.org_id == principal.org_id)
    breakdown: dict[str, dict[str, int]] = {}
    total = 0
    for analysis_type, level, count in db.execute(query).all():
        breakdown.setdefault(analysis_type, {})[level] = count
        total += count
    return {"total_analyses": total, "by_type_and_level": breakdown}
