"""Synthetic dataset generators.

DEMO/SIMULATION — every dataset produced here is synthetic (ADR-013). Each writes a
provenance header naming this generator, the seed and the generation time, so no
artefact in this repository can be mistaken for real-world agricultural data.
"""
from __future__ import annotations

import json
import math
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import numpy as np

GENERATOR = "ai/data/generate.py"
DATA_MARKING = "DEMO/SIMULATION — synthetic data generated by this repository. NOT real-world data."


def provenance(name: str, seed: int, **extra: Any) -> dict[str, Any]:
    return {
        "dataset": name,
        "marking": DATA_MARKING,
        "generator": GENERATOR,
        "seed": seed,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        **extra,
    }


# --------------------------------------------------------------------------- #
# Telemetry
# --------------------------------------------------------------------------- #
def _diurnal(hour: float, low: float, high: float, peak_hour: float = 14.0) -> float:
    mid, amplitude = (low + high) / 2, (high - low) / 2
    return mid + amplitude * math.sin((hour - peak_hour + 6) / 24 * 2 * math.pi)


def telemetry_reading(device_type: str, when: datetime, rng: random.Random,
                      drift: float = 0.0) -> dict[str, float]:
    """One physically plausible reading for a device class at a point in time."""
    hour = when.hour + when.minute / 60
    day_of_year = when.timetuple().tm_yday
    season = math.sin((day_of_year - 80) / 365 * 2 * math.pi)      # +1 midsummer

    if device_type == "SOIL_SENSOR":
        return {
            "soil_moisture_pct": round(max(0.0, min(100.0, 28 + 8 * season * -0.4
                                                    + rng.gauss(0, 2.5) + drift * 30)), 2),
            "soil_temp_c": round(_diurnal(hour, 8 + 6 * season, 18 + 10 * season)
                                 + rng.gauss(0, 0.7) + drift * 20, 2),
            "ph": round(min(14.0, max(0.0, 6.4 + rng.gauss(0, 0.15) + drift * 4)), 2),
            "nitrogen_ppm": round(max(0.0, 42 + rng.gauss(0, 6) + drift * 60), 1),
            "phosphorus_ppm": round(max(0.0, 24 + rng.gauss(0, 4)), 1),
            "potassium_ppm": round(max(0.0, 160 + rng.gauss(0, 18)), 1),
            "ec_ds_m": round(max(0.0, 1.3 + rng.gauss(0, 0.2)), 3),
        }
    if device_type == "WEATHER_STATION":
        return {
            "air_temp_c": round(_diurnal(hour, 6 + 8 * season, 19 + 11 * season)
                                + rng.gauss(0, 1.0) + drift * 25, 2),
            "humidity_pct": round(max(0.0, min(100.0, 70 - 20 * math.sin((hour - 3) / 24 * 2 * math.pi)
                                               + rng.gauss(0, 5))), 1),
            "rainfall_mm": round(max(0.0, rng.expovariate(1 / 0.6) if rng.random() < 0.18 else 0.0), 2),
            "wind_speed_ms": round(max(0.0, abs(rng.gauss(3.5, 2.0))), 2),
            "solar_w_m2": round(max(0.0, 900 * max(0.0, math.sin((hour - 6) / 12 * math.pi))
                                    + rng.gauss(0, 30)), 1),
        }
    if device_type == "DRONE":
        return {
            "altitude_m": round(max(0.0, 85 + rng.gauss(0, 12) + drift * 400), 1),
            "battery_pct": round(max(0.0, min(100.0, 74 + rng.gauss(0, 9) - drift * 40)), 1),
            "images_captured": float(rng.randint(20, 240)),
            "speed_ms": round(max(0.0, 8.5 + rng.gauss(0, 1.6) + drift * 20), 2),
        }
    if device_type == "YIELD_MONITOR":
        return {
            "yield_t_ha": round(max(0.0, 9.2 + rng.gauss(0, 1.4) + drift * 20), 2),
            "moisture_pct": round(max(0.0, min(100.0, 17 + rng.gauss(0, 1.8) + drift * 40)), 2),
            "speed_kmh": round(max(0.0, 6.4 + rng.gauss(0, 1.0)), 2),
            "swath_m": round(max(0.0, 7.5 + rng.gauss(0, 0.2)), 2),
        }
    if device_type == "IRRIGATION_CONTROLLER":
        running = rng.random() < 0.35
        return {
            "flow_l_min": round(max(0.0, (420 + rng.gauss(0, 30)) if running else rng.uniform(0, 3)), 1),
            "pressure_bar": round(max(0.0, (3.2 + rng.gauss(0, 0.25)) if running
                                      else 0.4 + rng.gauss(0, 0.1)), 2),
            "duration_s": float(rng.randint(600, 3600) if running else 0),
        }
    if device_type == "COLD_CHAIN_SENSOR":
        return {
            "temp_c": round(2.8 + rng.gauss(0, 0.6) + drift * 25, 2),
            "humidity_pct": round(max(0.0, min(100.0, 85 + rng.gauss(0, 3))), 1),
            "shock_g": round(max(0.0, abs(rng.gauss(0.4, 0.5))), 2),
        }
    raise ValueError(f"Unknown device type {device_type}")


def telemetry_series(device_type: str, count: int, seed: int = 42,
                     interval_minutes: int = 15,
                     start: datetime | None = None) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    start = start or datetime.now(timezone.utc) - timedelta(minutes=interval_minutes * count)
    series = []
    for i in range(count):
        when = start + timedelta(minutes=interval_minutes * i)
        series.append({"recorded_at": when.isoformat(),
                       "readings": telemetry_reading(device_type, when, rng)})
    return series


def anomalous_reading(device_type: str, seed: int = 7, mode: str = "spoof") -> dict[str, float]:
    """A reading an attacker or a failing sensor would produce."""
    rng = random.Random(seed)
    when = datetime.now(timezone.utc)
    if mode == "spoof":
        base = telemetry_reading(device_type, when, rng, drift=1.0)
    elif mode == "drift":
        base = telemetry_reading(device_type, when, rng, drift=0.55)
    elif mode == "stuck":
        base = {k: 0.0 for k in telemetry_reading(device_type, when, rng)}
    else:
        base = telemetry_reading(device_type, when, rng)
    return {k: round(v, 3) for k, v in base.items()}


# --------------------------------------------------------------------------- #
# Hazard sequence database (synthetic motifs — NOT real pathogen sequences)
# --------------------------------------------------------------------------- #
HAZARD_CATALOGUE = [
    ("Synthetic phytopathogen effector motif A", "PLANT_PATHOGEN", 5,
     "Synthetic stand-in for a bacterial effector associated with plant disease"),
    ("Synthetic phytopathogen effector motif B", "PLANT_PATHOGEN", 4,
     "Synthetic stand-in for a fungal virulence determinant"),
    ("Synthetic mycotoxin biosynthesis motif", "TOXIN", 5,
     "Synthetic stand-in for a mycotoxin biosynthetic gene cluster fragment"),
    ("Synthetic plant toxin precursor motif", "TOXIN", 4,
     "Synthetic stand-in for a toxin precursor coding region"),
    ("Synthetic aminoglycoside resistance marker", "ANTIBIOTIC_RESISTANCE", 3,
     "Synthetic stand-in for an antibiotic resistance selection marker"),
    ("Synthetic beta-lactamase-like marker", "ANTIBIOTIC_RESISTANCE", 3,
     "Synthetic stand-in for a resistance marker of regulatory concern in food crops"),
    ("Synthetic host-range expansion motif", "VIRULENCE_FACTOR", 5,
     "Synthetic stand-in for a determinant that broadens pathogen host range"),
    ("Synthetic virulence regulator motif", "VIRULENCE_FACTOR", 4,
     "Synthetic stand-in for a transcriptional regulator of virulence genes"),
    ("Synthetic gene-drive cassette marker", "DUAL_USE_MARKER", 5,
     "Synthetic stand-in for a gene-drive construct signature"),
    ("Synthetic dual-use expression cassette", "DUAL_USE_MARKER", 4,
     "Synthetic stand-in for an expression cassette used in dual-use constructs"),
]


def hazard_database(seed: int = 1337) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    records = []
    for index, (name, hazard_class, severity, description) in enumerate(HAZARD_CATALOGUE):
        length = rng.randint(420, 900)
        sequence = "".join(rng.choice("ACGT") for _ in range(length))
        records.append({
            "agent_name": name, "hazard_class": hazard_class, "severity": severity,
            "description": description, "sequence": sequence, "is_synthetic": True,
            "reference": f"SYN-HAZ-{index + 1:03d}",
        })
    return records


def benign_sequence(length: int = 900, seed: int = 99) -> str:
    """A plausible benign crop insert: promoter + coding region + terminator, synthetic."""
    rng = random.Random(seed)
    return "".join(rng.choice("ACGT") for _ in range(length))


def hazard_derived_sequence(hazard_sequence: str, divergence: float = 0.06,
                            seed: int = 5) -> str:
    """A mutated descendant of a hazard sequence — the case exact matching would miss."""
    rng = random.Random(seed)
    bases = list(hazard_sequence)
    for i in range(len(bases)):
        if rng.random() < divergence:
            bases[i] = rng.choice([b for b in "ACGT" if b != bases[i]])
    return "".join(bases)


# --------------------------------------------------------------------------- #
# Crop leaf imagery (procedural patches)
# --------------------------------------------------------------------------- #
CROP_CLASSES = ["HEALTHY", "LEAF_BLIGHT", "RUST", "NUTRIENT_DEFICIENCY"]


def leaf_patch(label: str, size: int = 48, rng: np.random.Generator | None = None) -> np.ndarray:
    """Procedurally generate an RGB leaf patch with class-characteristic texture."""
    rng = rng or np.random.default_rng(0)
    yy, xx = np.mgrid[0:size, 0:size] / size
    base = np.zeros((size, size, 3), dtype=np.float32)
    # Healthy leaf ground: green dominant with a vein gradient.
    base[..., 1] = 0.55 + 0.15 * np.sin(yy * 6) + rng.normal(0, 0.03, (size, size))
    base[..., 0] = 0.22 + 0.05 * xx + rng.normal(0, 0.03, (size, size))
    base[..., 2] = 0.18 + rng.normal(0, 0.03, (size, size))

    if label == "LEAF_BLIGHT":
        for _ in range(rng.integers(3, 7)):
            cy, cx = rng.uniform(0.15, 0.85, 2)
            radius = rng.uniform(0.08, 0.20)
            mask = ((yy - cy) ** 2 + (xx - cx) ** 2) < radius ** 2
            base[mask] = base[mask] * 0.35 + np.array([0.42, 0.32, 0.12], dtype=np.float32) * 0.65
    elif label == "RUST":
        for _ in range(rng.integers(25, 70)):
            cy, cx = rng.uniform(0.05, 0.95, 2)
            radius = rng.uniform(0.012, 0.032)
            mask = ((yy - cy) ** 2 + (xx - cx) ** 2) < radius ** 2
            base[mask] = np.array([0.62, 0.28, 0.08], dtype=np.float32)
    elif label == "NUTRIENT_DEFICIENCY":
        # Interveinal chlorosis: yellowing that spares the veins.
        chlorosis = (np.sin(yy * 22) ** 2) * rng.uniform(0.5, 0.9)
        base[..., 0] += 0.38 * chlorosis
        base[..., 1] += 0.22 * chlorosis
        base[..., 2] -= 0.06 * chlorosis

    return np.clip(base, 0.0, 1.0).astype(np.float32)


def crop_image_dataset(per_class: int = 180, size: int = 48, seed: int = 11):
    rng = np.random.default_rng(seed)
    images, labels = [], []
    for index, label in enumerate(CROP_CLASSES):
        for _ in range(per_class):
            images.append(leaf_patch(label, size, rng))
            labels.append(index)
    images_array = np.stack(images)
    labels_array = np.array(labels, dtype=np.int64)
    order = rng.permutation(len(labels_array))
    return images_array[order], labels_array[order]


# --------------------------------------------------------------------------- #
# Fraud training features
# --------------------------------------------------------------------------- #
def fraud_feature_rows(count: int = 600, seed: int = 21) -> np.ndarray:
    """Feature rows for the novelty model: mostly clean chains, as in reality."""
    rng = random.Random(seed)
    rows = []
    for _ in range(count):
        events = rng.randint(4, 9)
        rows.append([
            float(events), float(rng.uniform(200, 20000)), float(rng.randint(0, 3)),
            float(rng.randint(0, 2)), 0.0, 0.0,
            float(rng.uniform(1.0, 6.0)), float(rng.uniform(-1.0, 3.0)),
        ])
    return np.array(rows, dtype=float)


def write_json(path: str | Path, name: str, seed: int, payload: Any) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps({"provenance": provenance(name, seed), "data": payload},
                                 indent=2))
    return target
