"""AI/ML services for the platform.

REAL IMPLEMENTATION: all algorithms below are genuine implementations.
DEMO/SIMULATION: every dataset they are trained or matched against is synthetic
and generated by ai/data/generate.py (ADR-013). Metrics reported anywhere in this
project are metrics on synthetic data and do not predict real-world performance.
"""
