"""Application factory: middleware, exception handlers, routers and static hosting."""
from __future__ import annotations

import logging
import sys
import time
import uuid
from pathlib import Path

from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

from .core.config import get_settings
from .core.errors import AppError, RateLimited, app_error_handler, problem, unhandled_handler
from .core.logging_conf import (actor_id as actor_ctx, app_log, configure_logging,
                                correlation_id as correlation_ctx, log_event,
                                org_id as org_ctx)

settings = get_settings()

# The ledger and AI packages live at the repository root.
if str(settings.repo_root) not in sys.path:
    sys.path.insert(0, str(settings.repo_root))

configure_logging(settings.log_level)

# --- simple in-process metrics (Prometheus text format) --------------------
_metrics = {
    "requests_total": 0,
    "requests_by_status": {},
    "latency_sum_seconds": 0.0,
    "auth_failures_total": 0,
    "telemetry_ingested_total": 0,
    "rate_limited_total": 0,
}


@asynccontextmanager
async def lifespan(application: FastAPI):        # noqa: ANN001, ARG001
    log_event(app_log, logging.INFO, "application started", environment=settings.env,
              demo_mode=settings.demo_mode, api_prefix=settings.api_prefix)
    yield
    log_event(app_log, logging.INFO, "application stopped")


def create_app() -> FastAPI:
    application = FastAPI(
        lifespan=lifespan,
        title=settings.app_name,
        version="1.0.0",
        description=(
            "Agricultural Biotechnology Security Platform — precision farming protection, "
            "GMO traceability, and food supply chain security.\n\n"
            "**Markings:** the permissioned ledger runs single-node ordering "
            "(DEMO/SIMULATION); its cryptography is real. All AI models are trained on "
            "synthetic data generated by this repository."
        ),
        docs_url=None if settings.is_production else "/docs",
        redoc_url=None if settings.is_production else "/redoc",
        openapi_url=None if settings.is_production else "/openapi.json",
    )

    # --- middleware (order matters; see Backend.md §3) ---------------------
    @application.middleware("http")
    async def correlation_and_metrics(request: Request, call_next):    # noqa: ANN001
        correlation = request.headers.get("x-request-id") or str(uuid.uuid4())
        correlation_ctx.set(correlation)
        actor_ctx.set("-")
        org_ctx.set("-")
        started = time.perf_counter()

        content_length = request.headers.get("content-length")
        if content_length and content_length.isdigit() and int(content_length) > settings.max_body_bytes:
            return problem(413, "payload_too_large", "Payload too large",
                           f"Request body exceeds {settings.max_body_bytes} bytes")

        try:
            response = await call_next(request)
        except Exception:                                              # noqa: BLE001
            app_log.exception("unhandled error in middleware chain")
            response = problem(500, "internal_error", "Internal server error",
                               "An unexpected error occurred.")

        elapsed = time.perf_counter() - started
        _metrics["requests_total"] += 1
        _metrics["latency_sum_seconds"] += elapsed
        bucket = f"{response.status_code // 100}xx"
        _metrics["requests_by_status"][bucket] = _metrics["requests_by_status"].get(bucket, 0) + 1
        if response.status_code == 401:
            _metrics["auth_failures_total"] += 1
        if response.status_code == 429:
            _metrics["rate_limited_total"] += 1
        if request.url.path.endswith("/telemetry/ingest") and response.status_code == 202:
            _metrics["telemetry_ingested_total"] += 1

        response.headers["X-Request-ID"] = correlation
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Referrer-Policy"] = "no-referrer"
        response.headers["Permissions-Policy"] = "geolocation=(), microphone=(), camera=()"
        response.headers["Cache-Control"] = response.headers.get("Cache-Control", "no-store")
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; "
            "connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'none'; "
            "form-action 'self'; frame-ancestors 'none'")
        if settings.is_production:
            response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"

        if elapsed > 1.0:
            log_event(app_log, logging.WARNING, "slow request", path=request.url.path,
                      seconds=round(elapsed, 3))
        return response

    @application.middleware("http")
    async def access_recorder(request: Request, call_next):             # noqa: ANN001
        """Feed the agricultural data-theft detector (FR-A3)."""
        response = await call_next(request)
        principal = getattr(request.state, "principal", None)
        if principal is not None and request.url.path.startswith(settings.api_prefix):
            try:
                from .core.database import SessionLocal
                from .services import security_ops

                page_size = int(request.query_params.get("page_size", 0) or 0)
                with SessionLocal() as session:
                    security_ops.record_access(
                        session, principal.id, principal.org_id, request.url.path,
                        request.method, page_size, 0, response.status_code,
                        request.client.host if request.client else None,
                        cross_tenant_attempt=(response.status_code == 403))
                    session.commit()
            except Exception:                                           # noqa: BLE001
                pass                     # detection telemetry must never break a request
        return response

    application.add_middleware(
        CORSMiddleware,
        allow_origins=list(settings.cors_origins),
        allow_credentials=True,
        allow_methods=["GET", "POST", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "X-Request-ID", "X-Device-Id",
                       "X-Device-Timestamp", "X-Device-Nonce", "X-Device-Signature"],
        max_age=600,
    )

    # --- exception handlers ------------------------------------------------
    application.add_exception_handler(AppError, app_error_handler)
    application.add_exception_handler(Exception, unhandled_handler)

    @application.exception_handler(RequestValidationError)
    async def _validation_error(request: Request,                       # noqa: ANN001
                                exc: RequestValidationError) -> JSONResponse:
        """FastAPI's default body is `{"detail": [...]}`, which differs in shape from every
        other error this API returns. Callers must not have to branch on error shape, so
        schema failures are re-wrapped in the same RFC-7807 envelope with the offending
        fields listed under `errors`."""
        fields = []
        for error in exc.errors()[:20]:
            location = ".".join(str(part) for part in error.get("loc", ())
                                if part not in ("body", "query", "path"))
            fields.append({"field": location or "request",
                           "message": str(error.get("msg", ""))[:200]})
        return problem(422, "validation_failed", "Validation failed",
                       "One or more fields failed validation.", errors=fields)

    @application.exception_handler(RateLimited)
    async def _rate_limited(request: Request, exc: RateLimited) -> JSONResponse:   # noqa: ANN001
        response = await app_error_handler(request, exc)
        retry = exc.context.get("retry_after")
        if retry:
            response.headers["Retry-After"] = str(int(float(retry)) + 1)
        return response

    # --- routers -----------------------------------------------------------
    from .routers import (admin, ai, audit, biosecurity, blockchain, compliance, dashboard,
                          devices, farms, gmo, notifications, security_ops, supplychain,
                          telemetry, verify)
    from .routers import auth as auth_router

    prefix = settings.api_prefix
    for module in (auth_router, admin, farms, devices, telemetry, ai, security_ops, biosecurity,
                   gmo, supplychain, compliance, blockchain, audit, notifications, verify,
                   dashboard):
        application.include_router(module.router, prefix=prefix)

    # --- operational endpoints --------------------------------------------
    @application.get("/health", tags=["Operations"], summary="Liveness and readiness summary")
    def health() -> dict:
        return {"status": "ok", "app": settings.app_name, "version": "1.0.0",
                "environment": settings.env, "demo_mode": settings.demo_mode}

    @application.get("/health/live", tags=["Operations"], summary="Liveness probe")
    def live() -> dict:
        return {"status": "alive"}

    @application.get("/health/ready", tags=["Operations"], summary="Readiness probe")
    def ready() -> JSONResponse:
        checks: dict[str, str] = {}
        healthy = True
        try:
            from sqlalchemy import text

            from .core.database import engine

            with engine.connect() as connection:
                connection.execute(text("SELECT 1"))
            checks["database"] = "ok"
        except Exception as exc:                                        # noqa: BLE001
            checks["database"] = f"error: {type(exc).__name__}"
            healthy = False
        try:
            from .services import ledger_client

            stats = ledger_client.stats()
            checks["ledger"] = "ok" if stats.get("height", 0) > 0 else "degraded"
        except Exception as exc:                                        # noqa: BLE001
            checks["ledger"] = f"error: {type(exc).__name__}"
        return JSONResponse(status_code=200 if healthy else 503,
                            content={"status": "ready" if healthy else "not_ready",
                                     "checks": checks})

    @application.get("/metrics", tags=["Operations"], summary="Prometheus metrics")
    def metrics() -> PlainTextResponse:
        lines = [
            "# HELP absp_requests_total Total HTTP requests",
            "# TYPE absp_requests_total counter",
            f"absp_requests_total {_metrics['requests_total']}",
            "# HELP absp_request_latency_seconds_sum Cumulative request latency",
            "# TYPE absp_request_latency_seconds_sum counter",
            f"absp_request_latency_seconds_sum {_metrics['latency_sum_seconds']:.6f}",
            "# HELP absp_auth_failures_total Authentication failures",
            "# TYPE absp_auth_failures_total counter",
            f"absp_auth_failures_total {_metrics['auth_failures_total']}",
            "# HELP absp_rate_limited_total Rate-limited responses",
            "# TYPE absp_rate_limited_total counter",
            f"absp_rate_limited_total {_metrics['rate_limited_total']}",
            "# HELP absp_telemetry_ingested_total Telemetry messages accepted",
            "# TYPE absp_telemetry_ingested_total counter",
            f"absp_telemetry_ingested_total {_metrics['telemetry_ingested_total']}",
            "# HELP absp_responses_total Responses by status class",
            "# TYPE absp_responses_total counter",
        ]
        for bucket, count in sorted(_metrics["requests_by_status"].items()):
            lines.append(f'absp_responses_total{{status="{bucket}"}} {count}')
        try:
            from .services import ledger_client

            stats = ledger_client.stats()
            lines += ["# HELP absp_ledger_height Ledger block height",
                      "# TYPE absp_ledger_height gauge",
                      f"absp_ledger_height {stats.get('height', 0)}"]
        except Exception:                                               # noqa: BLE001
            pass
        return PlainTextResponse("\n".join(lines) + "\n")

    # --- frontend ----------------------------------------------------------
    frontend_dir = settings.repo_root / "frontend"
    if frontend_dir.is_dir():
        application.mount("/static", StaticFiles(directory=str(frontend_dir)), name="static")

        @application.get("/", include_in_schema=False)
        def index() -> FileResponse:
            return FileResponse(str(frontend_dir / "index.html"))

        @application.get("/verify.html", include_in_schema=False)
        def verify_page() -> FileResponse:
            return FileResponse(str(frontend_dir / "verify.html"))

        @application.get("/favicon.ico", include_in_schema=False)
        def favicon() -> FileResponse:
            """Browsers request /favicon.ico regardless of the <link> tag."""
            return FileResponse(str(frontend_dir / "assets" / "favicon.svg"),
                                media_type="image/svg+xml")

    return application


app = create_app()
