#!/usr/bin/env python3
"""Train every model artefact and write its model card.

All training data is synthetic (ADR-013). Metrics reported here describe the
synthetic task only.  Usage:  python3 scripts/train_models.py [--fast]
"""
from __future__ import annotations

import argparse
import json
import pickle
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ai.anomaly import FEATURES, extract_features                      # noqa: E402
from ai.data.generate import (CROP_CLASSES, crop_image_dataset,        # noqa: E402
                              fraud_feature_rows, telemetry_series)

MODEL_DIR = ROOT / "ai" / "models"
MARKING = "DEMO/SIMULATION — trained on synthetic data generated by ai/data/generate.py"


def _sha256(path: Path) -> str:
    import hashlib

    return hashlib.sha256(path.read_bytes()).hexdigest()


def train_anomaly_models(fast: bool) -> dict:
    from sklearn.ensemble import IsolationForest

    samples = 300 if fast else 1500
    summary = {}
    for device_type in FEATURES:
        series = telemetry_series(device_type, samples, seed=hash(device_type) % 10_000,
                                  interval_minutes=15)
        rows, previous = [], None
        for entry in series:
            when = datetime.fromisoformat(entry["recorded_at"])
            rows.append(extract_features(device_type, entry["readings"], previous, 900.0, when.hour))
            previous = entry["readings"]
        matrix = np.array(rows, dtype=float)
        model = IsolationForest(n_estimators=120, contamination=0.02, random_state=42)
        model.fit(matrix)
        path = MODEL_DIR / f"anomaly_{device_type.lower()}.joblib"
        with path.open("wb") as handle:
            pickle.dump(model, handle)
        inlier_rate = float((model.predict(matrix) == 1).mean())
        summary[device_type] = {"training_rows": len(rows), "features": matrix.shape[1],
                                "inlier_rate_on_training_data": round(inlier_rate, 4),
                                "artefact": path.name, "sha256": _sha256(path)}
        print(f"  anomaly[{device_type}]: {len(rows)} rows, inlier rate {inlier_rate:.3f}")
    return summary


def train_fraud_model(fast: bool) -> dict:
    from sklearn.ensemble import IsolationForest

    rows = fraud_feature_rows(200 if fast else 800)
    model = IsolationForest(n_estimators=120, contamination=0.05, random_state=42)
    model.fit(rows)
    path = MODEL_DIR / "fraud_if.joblib"
    with path.open("wb") as handle:
        pickle.dump(model, handle)
    print(f"  fraud: {len(rows)} rows")
    return {"training_rows": len(rows), "features": rows.shape[1],
            "artefact": path.name, "sha256": _sha256(path)}


def train_crop_vision(fast: bool) -> dict:
    import tensorflow as tf

    from ai.vision import build_model

    tf.keras.utils.set_random_seed(42)
    per_class = 90 if fast else 260
    images, labels = crop_image_dataset(per_class=per_class)
    split = int(len(labels) * 0.8)
    x_train, x_val = images[:split], images[split:]
    y_train, y_val = labels[:split], labels[split:]

    model = build_model()
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    epochs = 6 if fast else 14
    model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=epochs,
              batch_size=32, verbose=0)
    loss, accuracy = model.evaluate(x_val, y_val, verbose=0)

    predictions = np.argmax(model.predict(x_val, verbose=0), axis=1)
    confusion = np.zeros((len(CROP_CLASSES), len(CROP_CLASSES)), dtype=int)
    for true, predicted in zip(y_val, predictions):
        confusion[true][predicted] += 1

    path = MODEL_DIR / "crop_vision.keras"
    model.save(path)
    print(f"  crop_vision: val accuracy {accuracy:.3f} over {len(y_val)} samples")
    return {"train_samples": int(len(y_train)), "val_samples": int(len(y_val)),
            "epochs": epochs, "val_accuracy": round(float(accuracy), 4),
            "val_loss": round(float(loss), 4), "classes": CROP_CLASSES,
            "confusion_matrix": confusion.tolist(), "artefact": path.name,
            "sha256": _sha256(path)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fast", action="store_true", help="smaller datasets, fewer epochs")
    parser.add_argument("--skip-vision", action="store_true", help="skip the TensorFlow model")
    args = parser.parse_args()

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    print("Training models (synthetic data — see ADR-013)")

    anomaly = train_anomaly_models(args.fast)
    fraud = train_fraud_model(args.fast)
    vision = {"status": "skipped"} if args.skip_vision else train_crop_vision(args.fast)

    common = {"marking": MARKING, "trained_at": datetime.now(timezone.utc).isoformat(),
              "data_generator": "ai/data/generate.py",
              "limitations": [
                  "Trained exclusively on synthetic data; metrics do not predict field performance.",
                  "No real agricultural telemetry, imagery, or fraud labels were used.",
                  "Intended to demonstrate the complete AI workflow, not to be deployed as-is.",
                  "Training and validation images come from the same procedural generator, so a "
                  "high or even perfect validation score measures separability of the synthetic "
                  "classes, not generalisation to photographs of real leaves.",
                  "The --fast training path (6 epochs, 90 images per class) undertrains the "
                  "vision model and confuses LEAF_BLIGHT with RUST, whose synthetic textures "
                  "differ only in lesion scale. Use the default path for any reported figure.",
              ]}

    (MODEL_DIR / "anomaly_model_card.json").write_text(json.dumps(
        {**common, "model": "IsolationForest per device class", "purpose":
         "Detect compromised or failing agricultural devices (FR-A5)",
         "inputs": "Per-channel readings, deltas from the previous reading, interval, hour",
         "outputs": "Anomaly score 0-1, level, human-readable reasons",
         "fallback": "Deterministic range/delta rules when no artefact is present",
         "per_device_class": anomaly}, indent=2))

    (MODEL_DIR / "fraud_model_card.json").write_text(json.dumps(
        {**common, "model": "IsolationForest novelty component over event features",
         "purpose": "Supplement deterministic food-fraud rules (FR-D3)",
         "note": "Rules dominate the score; the model contributes a novelty term only (ADR-012)",
         "training": fraud}, indent=2))

    # --skip-vision leaves the existing .keras artefact in place, so it must also leave
    # that artefact's card in place: overwriting it with {"status": "skipped"} would
    # discard the real metrics for a model that is still being served.
    if not args.skip_vision:
        (MODEL_DIR / "crop_vision_model_card.json").write_text(json.dumps(
            {**common, "model": "Small CNN (TensorFlow/Keras)",
             "purpose": "Classify crop leaf condition from imagery",
             "inputs": "48x48x3 float image in [0,1]",
             "outputs": "Class label, confidence, per-class probabilities, agronomic advice",
             "fallback": "Documented colour-statistic classifier when no artefact is present",
             "training": vision}, indent=2))
    else:
        print("  crop_vision: skipped — existing artefact and model card left untouched")

    print(f"Artefacts and model cards written to {MODEL_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
